version: "2"
volumes:
    wallet_build: {}

services:
    web-wallet:
        build: .
        ports:
            - "8888:80"
        volumes:
            - wallet_build:/bitshares-ui/build/dist
            - .:/bitshares-ui
